CREATE TABLE green_point (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    item_id NUMBER,
    amount NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_green_point_member FOREIGN KEY (member_id) REFERENCES MEMBER(id),
    CONSTRAINT fk_green_point_item FOREIGN KEY (item_id) REFERENCES ITEM(id)
);