CREATE TABLE user_action_log(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    member_gender VARCHAR2(10) NOT NULL,
    member_age NUMBER NOT NULL,
    search_word VARCHAR2(255),
    item_id NUMBER,
    created_at DATE DEFAULT SYSDATE
    );