create table member (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        email VARCHAR2(256) NOT NULL UNIQUE,
                        password VARCHAR2(256),
                        provider VARCHAR2(24) NOT NULL,
                        nickname VARCHAR2(32) NOT NULL ,
                        profile_image VARCHAR2(512),
                        is_signup_completed VARCHAR2(2) DEFAULT 'N',
                        gender VARCHAR2(2),
                        age_range VARCHAR2(12),
                        created_at DATE DEFAULT SYSDATE NOT NULL,
                        updated_at DATE DEFAULT SYSDATE NOT NULL
);

create table refresh_token
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    refresh_token VARCHAR2(512) NOT NULL ,
    member_id NUMBER NOT NULL ,
    created_at DATE DEFAULT SYSDATE NOT NULL
);