CREATE TABLE item_category (
                                  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                  name VARCHAR2(100) NOT NULL,
                                  created_at DATE DEFAULT SYSDATE NOT NULL,
                                  updated_at DATE DEFAULT SYSDATE NOT NULL
);
