CREATE TABLE item (
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         category_id NUMBER NOT NULL,
                         brand_id NUMBER NOT NULL,
                         product_name VARCHAR2(200) NOT NULL,
                         price NUMBER NOT NULL,
                         origin VARCHAR2(100) NOT NULL,
                         discount NUMBER DEFAULT 0 NOT NULL,
                         quantity NUMBER DEFAULT 0 NOT NULL CHECK (quantity >= 0),
                         created_at DATE DEFAULT SYSDATE NOT NULL,
                         updated_at DATE DEFAULT SYSDATE NOT NULL,
                         description CLOB,
                         is_green VARCHAR2(2) DEFAULT 'N' NOT NULL CHECK (is_green IN ('Y', 'N')),
                         thumbnail_image VARCHAR2(512),

                         CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES item_category(id),
                         CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand(id)
);

