CREATE TABLE shopping_basket (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,

    CONSTRAINT fk_shopping_basket_member FOREIGN KEY (member_id) REFERENCES member(id)
);