ALTER TABLE ITEM_CATEGORY ADD english_name VARCHAR2(255);

UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='fruit_veg' WHERE ID = 1;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='crop' WHERE ID = 2;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='fish' WHERE ID = 3;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='meat' WHERE ID = 4;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='rice' WHERE ID = 5;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='side_dish' WHERE ID = 6;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='sauce' WHERE ID = 7;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='bread_cheeze' WHERE ID = 8;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='snack' WHERE ID = 9;
UPDATE ITEM_CATEGORY SET ENGLISH_NAME ='nutrition' WHERE ID = 10;

ALTER TABLE ITEM_CATEGORY MODIFY english_name VARCHAR2(255) NOT NULL;

COMMIT;