CREATE TABLE basket_item (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shopping_basket_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1 NOT NULL CHECK (quantity > 0),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_basket_item_basket FOREIGN KEY (shopping_basket_id) REFERENCES shopping_basket(id),
    CONSTRAINT fk_basket_item_item   FOREIGN KEY (item_id) REFERENCES item(id)
);