CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    order_number VARCHAR2(60) NOT NULL UNIQUE,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    destination VARCHAR2(1024) NOT NULL,
    receiver_name VARCHAR2(20) NOT NULL,
    receiver_tel VARCHAR2(30) NOT NULL,
    request VARCHAR2(512),
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (
        status IN ('PENDING', 'PAID', 'FAILED')
    ),

    CONSTRAINT fk_order_member FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE order_item (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_item_item FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE payment (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    card_number VARCHAR2(24) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    bank VARCHAR2(50) NOT NULL,

    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id)
);